/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projetopetshop.screens;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroDono extends javax.swing.JDialog {

    /**
     * Creates new form CadastroDono
     * @param parent
     * @param modal
     */
    public CadastroDono(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo( null );   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobrenome = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        optSolteiro = new javax.swing.JRadioButton();
        optCasado = new javax.swing.JRadioButton();
        optViuvo = new javax.swing.JRadioButton();
        cboEstado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        cboSexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chkBanho = new javax.swing.JCheckBox();
        chkTosa = new javax.swing.JCheckBox();
        chkHospedagem = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Dono");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Sobrenome:");

        jLabel3.setText("CEP:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });

        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        optSolteiro.setText("Solteiro");
        optSolteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSolteiroActionPerformed(evt);
            }
        });

        optCasado.setText("Casado");
        optCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCasadoActionPerformed(evt);
            }
        });

        optViuvo.setText("Viuvo");
        optViuvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optViuvoActionPerformed(evt);
            }
        });

        cboEstado.setText("Estado civil:");

        jLabel5.setText("Numero:");

        jLabel6.setText("E-mail:");

        jLabel7.setText("CPF:");

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outros", "Feminino", "Masculino" }));
        cboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSexoActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo:");

        jLabel9.setText("Motivo do cadastro:");

        chkBanho.setText("Banho");

        chkTosa.setText("Tosa");

        chkHospedagem.setText("Hospedagem");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(txtCep)
                        .addComponent(txtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optSolteiro)
                            .addComponent(optViuvo))
                        .addGap(18, 18, 18)
                        .addComponent(optCasado))
                    .addComponent(cboEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkTosa))
                    .addComponent(jLabel5)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkHospedagem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(45, 45, 45)
                        .addComponent(btnExcluir)
                        .addGap(45, 45, 45)
                        .addComponent(btnSalvar)
                        .addGap(45, 45, 45)
                        .addComponent(btnCancelar)))
                .addGap(45, 45, 45)
                .addComponent(btnFechar)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstado)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optSolteiro)
                    .addComponent(optCasado)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optViuvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBanho)
                    .addComponent(chkTosa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHospedagem)
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void optCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCasadoActionPerformed

    private void optSolteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSolteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSolteiroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(optCasado);
        grupo.add(optSolteiro);
        grupo.add(optViuvo);
        
        limpaComponentes();
        desabilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void optViuvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optViuvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optViuvoActionPerformed

    private void cboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSexoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo Nome é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
        } else if (txtSobrenome.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo Sobrenome é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
            txtSobrenome.requestFocus();
        } else if (txtCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo CEP é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);                    
            txtCep.requestFocus();
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo Numero é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
            txtNumero.requestFocus();
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo E-mail é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();    
        } else if (txtCpf.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "O campo CPF é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
        }else if (!optSolteiro.isSelected() && !optCasado.isSelected() && !optViuvo.isSelected()) {
            JOptionPane.showMessageDialog(null,
                    "O campo Estado Civil é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
        }else if (cboSexo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                    "O campo Sexo é obrigatório!",
                    "Validação", JOptionPane.ERROR_MESSAGE);
            cboSexo.requestFocus();
        } else {
            // aqui se verifica se é um novo registro ou atualização de um já 
            // existente. isso define se é um update ou um insert
           
            JOptionPane.showMessageDialog(null,
                    "Registro inserido ou atualizado com sucesso!",
                    "Validação", JOptionPane.INFORMATION_MESSAGE);
            limpaComponentes();
            desabilitaComponentes();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

        
    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
         limpaComponentes();
         habilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja excluir?",
                "Confirmação", JOptionPane.OK_CANCEL_OPTION);
        if (resposta == JOptionPane.OK_OPTION) {
            // executa um delete no banco de dados
            // 
            //
            JOptionPane.showMessageDialog(null,
                    "Registro foi excluído com sucesso!",
                    "Validação", JOptionPane.INFORMATION_MESSAGE);
            limpaComponentes();
            desabilitaComponentes();
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaComponentes();
        desabilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel cboEstado;
    private javax.swing.JComboBox<String> cboSexo;
    private javax.swing.JCheckBox chkBanho;
    private javax.swing.JCheckBox chkHospedagem;
    private javax.swing.JCheckBox chkTosa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton optCasado;
    private javax.swing.JRadioButton optSolteiro;
    private javax.swing.JRadioButton optViuvo;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables

    private void limpaComponentes() {
        txtNome.setText("");
        txtSobrenome.setText("");
        txtCep.setText("");
        txtNumero.setText("");
        txtEmail.setText("");
        txtCpf.setText("");
        cboSexo.setSelectedItem(null);
        optSolteiro.setSelected(false);
        optCasado.setSelected(false);
        optViuvo.setSelected(false);
        chkBanho.setSelected(false);
        chkTosa.setSelected(false);    
        chkHospedagem.setSelected(false); 
    }

    private void desabilitaComponentes() {
        txtNome.setEnabled(false);
        txtSobrenome.setEnabled(false);
        txtCep.setEnabled(false);
        txtNumero.setEnabled(false);
        txtEmail.setEnabled(false);
        txtCpf.setEnabled(false);
        cboSexo.setEnabled(false);
        optSolteiro.setEnabled(false);
        optCasado.setEnabled(false);
        optViuvo.setEnabled(false);
        chkBanho.setEnabled(false);
        chkTosa.setEnabled(false);    
        chkHospedagem.setEnabled(false);
        
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnFechar.setEnabled(true);
    }

    private void habilitaComponentes() {
        txtNome.setEnabled(true);
        txtSobrenome.setEnabled(true);
        txtCep.setEnabled(true);
        txtNumero.setEnabled(true);
        txtEmail.setEnabled(true);
        txtCpf.setEnabled(true);
        cboSexo.setEnabled(true);
        optSolteiro.setEnabled(true);
        optCasado.setEnabled(true);
        optViuvo.setEnabled(true);
        chkBanho.setEnabled(true);
        chkTosa.setEnabled(true);    
        chkHospedagem.setEnabled(true);
        
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnFechar.setEnabled(false);     
    }
}
