/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projetopetshop.screens;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroPet extends javax.swing.JDialog {

    /**
     * Creates new form CadastroPet
     */
    public CadastroPet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo( null );   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRaça = new javax.swing.JTextField();
        chkBanho = new javax.swing.JCheckBox();
        chkHospedagem = new javax.swing.JCheckBox();
        chkTosa = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        optCastradoSim = new javax.swing.JRadioButton();
        optCastradoNao = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        cboPorte = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboEspecie = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtObservacoes = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Pet");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Espécie:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Raça:");

        chkBanho.setText("Banho");

        chkHospedagem.setText("Hospedagem");

        chkTosa.setText("Tosa");

        jLabel4.setText("Serviço de interesse para o pet:");

        optCastradoSim.setText("Sim");
        optCastradoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCastradoSimActionPerformed(evt);
            }
        });

        optCastradoNao.setText("Não");

        jLabel5.setText("Castrado?");

        jLabel6.setText("Idade:");

        cboPorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Pequeno", "Medio", "Grande" }));

        jLabel7.setText("Porte:");

        cboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Cachorro", "Gatos", "Répteis", "Roedores", "Afíbios" }));

        jLabel8.setText("Observações sobre o pet:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdade)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtNome)
                            .addComponent(jLabel1)
                            .addComponent(txtRaça)
                            .addComponent(jLabel6)
                            .addComponent(cboEspecie, 0, 125, Short.MAX_VALUE))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optCastradoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optCastradoNao))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(chkHospedagem)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(chkTosa))
                            .addComponent(cboPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(chkBanho)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtObservacoes, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addGap(45, 45, 45)
                .addComponent(btnExcluir)
                .addGap(45, 45, 45)
                .addComponent(btnSalvar)
                .addGap(45, 45, 45)
                .addComponent(btnCancelar)
                .addGap(45, 45, 45)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optCastradoSim)
                    .addComponent(optCastradoNao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBanho, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkTosa))
                        .addGap(18, 18, 18)
                        .addComponent(chkHospedagem)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cboPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRaça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optCastradoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCastradoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCastradoSimActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(optCastradoSim);
        grupo.add(optCastradoNao);
        
        limpaComponentes();
        desabilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                "O campo Nome é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
        } else if (txtRaça.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                "O campo Raça é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            txtRaça.requestFocus();
        } else if (txtIdade.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                "O campo Idade é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            txtIdade.requestFocus();
        } else if (txtObservacoes.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                "O campo Observações sobre o pet é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            txtObservacoes.requestFocus();
        }else if (!optCastradoSim.isSelected() && !optCastradoNao.isSelected()) {
            JOptionPane.showMessageDialog(null,
                "O campo Castrado é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
        }else if (cboEspecie.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                "O campo Especie é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            cboEspecie.requestFocus();
        }else if (cboPorte.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                "O campo Porte é obrigatório!",
                "Validação", JOptionPane.ERROR_MESSAGE);
            cboPorte.requestFocus();
        } else {
            // aqui se verifica se é um novo registro ou atualização de um já
            // existente. isso define se é um update ou um insert

            JOptionPane.showMessageDialog(null,
                "Registro inserido ou atualizado com sucesso!",
                "Validação", JOptionPane.INFORMATION_MESSAGE);
            limpaComponentes();
            desabilitaComponentes();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaComponentes();
        habilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null,
            "Tem certeza que deseja excluir?",
            "Confirmação", JOptionPane.OK_CANCEL_OPTION);
        if (resposta == JOptionPane.OK_OPTION) {
            // executa um delete no banco de dados
            //
            //
            JOptionPane.showMessageDialog(null,
                "Registro foi excluído com sucesso!",
                "Validação", JOptionPane.INFORMATION_MESSAGE);
            limpaComponentes();
            desabilitaComponentes();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaComponentes();
        desabilitaComponentes();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPet dialog = new CadastroPet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboEspecie;
    private javax.swing.JComboBox<String> cboPorte;
    private javax.swing.JCheckBox chkBanho;
    private javax.swing.JCheckBox chkHospedagem;
    private javax.swing.JCheckBox chkTosa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton optCastradoNao;
    private javax.swing.JRadioButton optCastradoSim;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JTextField txtRaça;
    // End of variables declaration//GEN-END:variables

    private void limpaComponentes() {
        txtNome.setText("");
        txtRaça.setText("");
        txtIdade.setText("");
        txtObservacoes.setText("");
        cboEspecie.setSelectedItem(null);
        cboPorte.setSelectedItem(null);
        optCastradoSim.setSelected(false);
        optCastradoNao.setSelected(false);
        chkBanho.setSelected(false);
        chkTosa.setSelected(false);    
        chkHospedagem.setSelected(false); }

    private void habilitaComponentes() {
        txtNome.setEnabled(true);
        txtRaça.setEnabled(true);
        txtIdade.setEnabled(true);
        txtObservacoes.setEnabled(true);
        cboEspecie.setEnabled(true);
        cboPorte.setEnabled(true);
        optCastradoSim.setEnabled(true);
        optCastradoNao.setEnabled(true);
        chkBanho.setEnabled(true);
        chkTosa.setEnabled(true);    
        chkHospedagem.setEnabled(true);
        
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnFechar.setEnabled(false);  }

    private void desabilitaComponentes() {
        txtNome.setEnabled(false);
        txtRaça.setEnabled(false);
        txtIdade.setEnabled(false);
        txtObservacoes.setEnabled(false);
        cboEspecie.setEnabled(false);
        cboPorte.setEnabled(false);
        optCastradoSim.setEnabled(false);
        optCastradoNao.setEnabled(false);
        chkBanho.setEnabled(false);
        chkTosa.setEnabled(false);    
        chkHospedagem.setEnabled(false);
        
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnFechar.setEnabled(true);}
}
